### ISSUE TITLE
Add support for compression.

### ISSUE THREAD

**Issue by jonatino** [vincent-herlemont/native_db#137]
Would be nice to support compression for db's that have strings and other easily compressible formats. Perhaps just add optional gzip compression to the db?

**Comment by vincent-herlemont** [comment]
>  db's that have strings and other easily compressible formats.

@jonatino The database stores only data serialized by [`native_model`](https://github.com/vincent-herlemont/native_model
). There are no strings that are directly recorded in the database.

However, it would be necessary to list and study the implementations and understand how compression is implemented in other databases in order to have a state of the art understanding of compression techniques for databases.

On my side, it's not a priority, but if you want to start, I support you :)

**Comment by vincent-herlemont** [comment]
I am closing this issue for now; it is not planned, but if someone wants to work on this problem, a PR and a reopening of this issue is possible.
