### ISSUE TITLE
Database has reference to DatabaseBuilder ?

### ISSUE THREAD

**Issue by dai1975** [vincent-herlemont/native_db#138]
```
struct Connection {
  db: Database,
}
fn new() -> Connection {
  let mut builder = DatabaseBuilder::new();
  builder.define::<Data>();
  let db = builder.create(...);
  Conection { db }
```

It fails because &builder is not long alive.
There may some solution for this problem, such that use self referencing structure technique or make database builder to be 'static.

But I think it would better that Database implementation simply copy DatabaseBuilder's infomation instead of holding reference to a builder. How about?

**Comment by vincent-herlemont** [comment]
It's true that DatabaseBuilder and Database are linked.

DatabaseBuilder initializes the tables. And the tables are instances of [`redb::TableDefinition`](https://github.com/cberner/redb/blob/cae8038e197e612b020146e9bcffbb13e1f358ad/src/db.rs#L111-L131) (the data layer used for Native DB is [redb](https://github.com/cberner/redb/)). The field `name: &'a str` is a reference. The `DatabaseBuilder` stores the reference values to the table names, which causes the link between `DatabaseBuilder` and `Database`.

> There may some solution for this problem, such that use self referencing structure technique or make database builder to be 'static.

I don't think it's advisable to use a self-referencing structure technique because Rust seems to inherently prohibit it. And making it static seems too restrictive.

> But I think it would better that Database implementation simply copy DatabaseBuilder's infomation instead of holding reference to a builder. 

It seems that since what is linked is internal to the redb mechanism, I cannot go against it. @dai1975 What do you think, do you have any ideas?



---

These other threads might be interesting:
- https://github.com/cberner/redb/issues/558
- https://github.com/vincent-herlemont/native_db/discussions/69#discussioncomment-7929593

**Comment by Qbicz** [comment]
Hi @vincent-herlemont , I bump into the same problem as dai1975.
I want to keep `Database` and `DatabaseBuilder` in a module, and don't require user to create a long-lived instance of `DatabaseBuilder` in their top-level main.

Can you suggest any design approach that will allow me to include native_db in my project?
```
pub struct MyType<'a> {
    db: Database<'a>,
}
```

**Comment by Qbicz** [comment]
I thought the weak part was having to `use native_db::DatabaseBuilder` by the user, but I can actually re-export it like 
```
pub use native_db::DatabaseBuilder;
```
so user only needs to `use Db::{Db, DatabaseBuilder}`

**Comment by dai1975** [comment]
Hi @Qbicz , below code(self reference structure pattern) may work.

```
pub struct Connection<'a> {
  pub db: Database<'a>,
  _builder: *const DatabaseBuilder,
  _pinned: PhantomPinned,
}

impl<'a> Connection<'a> {
  pub fn new<P: AsRef<Path>>(path: P) -> Result<Pin<Box<Self>>> {
    let builder = Box::leak::<'a>(Box::new(DatabaseBuilder::new()));
    builder.define::<TYPE>()?;
    let db = builder.create(path)?;
    Ok(Box::pin(Self {
      db,
      _builder: builder as *const DatabaseBuilder,
      _pinned: PhantomPinned,
    }))
  }                                                                                                                                                                                                                                                                                 
  fn drop_pinned(self: Pin<&mut Self>) {
    let _ = unsafe { Box::from_raw(self._builder as *mut DatabaseBuilder) };                                                              }                                                                                                                                     
  }
}
impl<'a> std::ops::Drop for Connection<'a> {
  fn drop(&mut self) {
    unsafe { Pin::new_unchecked(self).drop_pinned(); }
}
```

**Comment by Qbicz** [comment]
Thank you @dai1975 for the example!
For now I prefer to re-export the DatabaseBuilder and enjoy the safety guarantees from the Rust compiler.
